server:
  port: 8081
spring:
  application:
    name: "loan-applications"
  devtools:
    add-properties: false
  flyway:
    enabled: true
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:credi_ya_db_app}"
    user: "${DB_USER:crediya_user}"
    password: "${DB_PASSWORD:crediya_password.}"
    default-schema: "${DB_SCHEMA:ms_applications}"
    schemas: "${DB_SCHEMA:ms_users}"
    create-schemas: false
    locations: "classpath:db/migration"
    baseline-on-migrate: false
    encoding: "UTF-8"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${AUTH_JWKS_URI:http://localhost:8080}/.well-known/jwks.json"
          issuer-uri: "${AUTH_ISSUER_URI:http://localhost:8080}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:5433}"
    database: "${DB_NAME:credi_ya_db_docker}"
    schema: "${DB_SCHEMA:ms_applications}"
    username: "${DB_USER:crediya_user_docker}"
    password: "${DB_PASSWORD:S3cre7.}"
  email-validator:
    base_url: "${EMAIL_VALIDATOR_BASE_URL:http://localhost:8080}"
    connect_timeout: "${EMAIL_VALIDATOR_CONNECT_TIMEOUT:10000}"
    read_timeout: "${EMAIL_VALIDATOR_READ_TIMEOUT:10000}"
    default_retry_attempts: "${EMAIL_VALIDATOR_DEFAULT_RETRY_ATTEMPTS:1}"
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}"
adapter:
  sqs:
    region: "us-east-1"
    requestQueueUrl: "${SQS_REQUEST_QUEUE:https://sqs.us-east-1.amazonaws.com/0000000000/laon_request_queue}"
    automaticQueueUrl: "${SQS_AUTOMATIC_QUEUE:https://sqs.us-east-1.amazonaws.com/0000000000/loan_automatic_queue}"
    reportQueueUrl: "${SQS_REPORT_QUEUE:https://sqs.us-east-1.amazonaws.com/0000000000/loan_reports_queue}"
entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "${SQS_RESULT_AUTOMATIC_QUEUE:https://sqs.us-east-1.amazonaws.com/0000000000/result_automatic_queue}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 30
    numberOfThreads: 1
