package com.crediya.loan.model.common.exceptions;

public enum ErrorCode {
    REQUIRED_FIELD,
    INVALID_FORMAT,
    INVALID_LENGTH,
    PERSISTENCE_ERROR,
    BUSINESS_RULE_VIOLATION,
    EMAIL_MISMATCH,
    EXTERNAL_SERVICE_ERROR,
    EXTERNAL_SERVICE_TIMEOUT,
    EXTERNAL_SERVICE_UNAVAILABLE,
    UNKNOWN
}
